// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import ()

type Movie struct {
	ID          string `db:"id" json:"id"`
	Title       string `db:"title" json:"title"`
	Description string `db:"description" json:"description"`
	Director    string `db:"director" json:"director"`
}

type Rating struct {
	ID         int64  `db:"id" json:"id"`
	MovieID    string `db:"movie_id" json:"movie_id"`
	RecordType string `db:"record_type" json:"record_type"`
	UserID     string `db:"user_id" json:"user_id"`
	Value      int32  `db:"value" json:"value"`
}
