// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"context"
)

type Querier interface {
	CreateMovie(ctx context.Context, arg *CreateMovieParams) (*Movie, error)
	CreateRating(ctx context.Context, arg *CreateRatingParams) (*Rating, error)
	DeleteMovie(ctx context.Context, id string) error
	DeleteRating(ctx context.Context, id int64) error
	GetMovie(ctx context.Context, id string) (*Movie, error)
	GetRating(ctx context.Context, id int64) (*Rating, error)
	ListMovies(ctx context.Context, arg *ListMoviesParams) ([]*Movie, error)
	ListRatings(ctx context.Context, arg *ListRatingsParams) ([]*Rating, error)
	UpdateMovie(ctx context.Context, arg *UpdateMovieParams) (*Movie, error)
	UpdateRating(ctx context.Context, arg *UpdateRatingParams) (*Rating, error)
}

var _ Querier = (*Queries)(nil)
